### PR TITLE
build-sys: don't generate introspection xml by running the program

### PR DESCRIPTION
**Pull request by fsateler**
Instead, embed the xml file into the binary. This should make both
cross-compiling and editing the introspection xml easier.

### CODE REVIEW

**Comment by fsateler** [comment]
the embedded file is in the .data section. Is that readonly?

**Comment by fsateler** [comment]
instrospect_xml is in `.data.rel.ro`. It appears .data is mutable

**Comment by heftig** [comment]
Yes, `.rodata` is the section we want.

I found https://www.devever.net/~hl/incbin; I think we want to use `objcopy` with the mentioned `--rename-section` tweak.

**Comment by heftig** [comment]
On the other hand, automake should already have support for compiling .s/.S assembly files so using `.incbin` might be a bit easier than adding an `AC_CHECK_PROG` check for objcopy to configure.ac.

**Pull request merged**
